steps:
# 1. Image bauen und in die Artifact Registry taggen
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - '${_IMAGE_PATH}:${SHORT_SHA}'
  - '.' # Baut den Container im aktuellen Verzeichnis
  id: Build

# 2. Image in die Artifact Registry pushen
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - '${_IMAGE_PATH}:${SHORT_SHA}'
  id: Push
 
# 3. Deployment auf Cloud Run
# HINWEIS: Das Service Account ist hier hartkodiert, um den Logging-Fehler im Trigger zu umgehen.
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - '${_SERVICE_NAME}'
  - '--image=${_IMAGE_PATH}:${SHORT_SHA}'
  - '--region=${_REGION}'
  - '--platform=managed'
  - '--service-account=smartmeal-run-sa@smartmeal-476022.iam.gserviceaccount.com' # Der Cloud Run Service Account wird hart kodiert.
  - '--allow-unauthenticated'
  - '--set-env-vars=NODE_ENV=production,REGION=${_REGION},PROJECT_ID=${_PROJECT_ID}'
  id: Deploy

# Diese Variablen werden vom Cloud Build Trigger an das Skript übergeben:
substitutions:
  _SERVICE_NAME: smartmeal-ai
  _PROJECT_ID: smartmeal-476022
  _REGION: europe-west3
  # WICHTIG: Die Variable _SA_EMAIL wird hier entfernt, um den Trigger-Konflikt zu vermeiden.
  _IMAGE_PATH: europe-west3-docker.pkg.dev/smartmeal-476022/smartmeal-repo/smartmeal-ai
