steps:
# 1. Das Docker-Image basierend auf dem Dockerfile bauen
#    Der Tag enthält die Substitutionsvariablen, die vom Trigger übergeben wurden.
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - '${_IMAGE_PATH}:${SHORT_SHA}'
  - '.' # Baut den Container im aktuellen Verzeichnis

# 2. Das Image in die Google Artifact Registry pushen
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - '${_IMAGE_PATH}:${SHORT_SHA}'

# 3. Den Cloud Run Service mit dem neuen Image aktualisieren
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - '${_SERVICE_NAME}' # smartmeal-ai
  - '--image=${_IMAGE_PATH}:${SHORT_SHA}'
  - '--region=${_REGION}' # europe-west3
  - '--platform=managed'
  - '--service-account=${_SA_EMAIL}' # smartmeal-run-sa@...
  - '--allow-unauthenticated'
  - '--set-env-vars=NODE_ENV=production,REGION=${_REGION},PROJECT_ID=${_PROJECT_ID}'
  
# Diese Variablen werden vom Cloud Build Trigger an das Skript übergeben:
substitutions:
  _SERVICE_NAME: smartmeal-ai
  _PROJECT_ID: smartmeal-476022
  _REGION: europe-west3
  _SA_EMAIL: smartmeal-run-sa@smartmeal-476022.iam.gserviceaccount.com
  _IMAGE_PATH: europe-west3-docker.pkg.dev/smartmeal-476022/smartmeal-repo/smartmeal-ai
